# Quarterly objectives with repos and contributors per objective
# Auto-generated by `uv run generate_config.py` from GitHub issues. Do not edit by hand.
# PI date ranges are maintained separately in constants.py
# - Objectives: Issues with pi-X.Y-objective labels
# - Contributors: Issue assignees
# - Repos: Labels matching repo:org/repo-name
OBJECTIVES = {
    "pi-25.2": [
        {
            "issue_number": 31,
            "title": "ODD PI 25.2 Objective 7: Increase data format support in VirtualiZarr",
            "state": "closed",
            "contributors": [
                ("Chuck Daniels", "chuckwondo"),
                ("Max Jones", "maxrjones"),
            ],
            "repos": [],
        },
        {
            "issue_number": 34,
            "title": "ODD PI 25.2 Objective 3: Visualize OCO-3 Datasets in VEDA",
            "state": "closed",
            "contributors": [
                ("Aimee Barciauskas", "abarciauskas-bgse"),
            ],
            "repos": [],
        },
        {
            "issue_number": 35,
            "title": "ODD PI 25.2 Objective 5: Deliver Virtual Zarr Stores for NASA Datasets Using Icechunk",
            "state": "closed",
            "contributors": [
                ("Aimee Barciauskas", "abarciauskas-bgse"),
            ],
            "repos": [],
        },
        {
            "issue_number": 36,
            "title": "ODD PI 25.2 Objective 6: Support for Modernizing VirtualiZarr to use zarr-python 3.0",
            "state": "closed",
            "contributors": [
                ("Sean Harkins", "sharkinsspatial"),
                ("Aimee Barciauskas", "abarciauskas-bgse"),
            ],
            "repos": [],
        },
        {
            "issue_number": 37,
            "title": "ODD PI 25.2 Objective 8: Support CMR Modernization",
            "state": "closed",
            "contributors": [
                ("Sean Harkins", "sharkinsspatial"),
                ("Kyle Barron", "kylebarron"),
            ],
            "repos": [],
        },
        {
            "issue_number": 40,
            "title": "ODD PI 25.2 Objective 1: Upgrade titiler and titiler-xarray to zarr-Python 3.0 and deploy to staging",
            "state": "closed",
            "contributors": [
                ("Max Jones", "maxrjones"),
            ],
            "repos": [],
        },
        {
            "issue_number": 41,
            "title": "ODD PI 25.2 Objective 4: Draft Web-Optimized Zarr (WOZ) Standard",
            "state": "closed",
            "contributors": [
                ("Max Jones", "maxrjones"),
            ],
            "repos": [],
        },
        {
            "issue_number": 76,
            "title": "ODD PI 25.2 Objective 2: Demonstrate how to tile HLS using titiler-cmr",
            "state": "closed",
            "contributors": [
                ("Henry Rodman", "hrodmn"),
            ],
            "repos": [],
        },
    ],
    "pi-25.3": [
        {
            "issue_number": 118,
            "title": "ODD PI 25.3 Objective 1: Support CMR Modernization",
            "state": "closed",
            "contributors": [
                ("Sean Harkins", "sharkinsspatial"),
                ("Kyle Barron", "kylebarron"),
            ],
            "repos": [],
        },
        {
            "issue_number": 119,
            "title": "ODD PI 25.3 Objective 2: Continue to Build Out the VirtualiZarr Ecosystem",
            "state": "closed",
            "contributors": [
                ("Sean Harkins", "sharkinsspatial"),
                ("Max Jones", "maxrjones"),
            ],
            "repos": [],
        },
        {
            "issue_number": 124,
            "title": "ODD PI 25.3 Objective 3: Publish Cloud-Optimized Datasets",
            "state": "closed",
            "contributors": [
                ("Chuck Daniels", "chuckwondo"),
                ("Aimee Barciauskas", "abarciauskas-bgse"),
            ],
            "repos": [],
        },
        {
            "issue_number": 126,
            "title": "ODD PI 25.3 Objective 4: Support TiTiler-CMR Adoption",
            "state": "closed",
            "contributors": [
                ("Sean Harkins", "sharkinsspatial"),
                ("Henry Rodman", "hrodmn"),
            ],
            "repos": [],
        },
        {
            "issue_number": 127,
            "title": "ODD PI 25.3 Objective 6: Community Involvement",
            "state": "closed",
            "contributors": [
                ("Max Jones", "maxrjones"),
                ("Aimee Barciauskas", "abarciauskas-bgse"),
                ("Henry Rodman", "hrodmn"),
            ],
            "repos": [],
        },
        {
            "issue_number": 165,
            "title": "ODD PI 25.3 Objective 5: Foundational Zarr-Python and Xarray Contributions",
            "state": "closed",
            "contributors": [
                ("Davis Bennett", "d-v-b"),
                ("Max Jones", "maxrjones"),
            ],
            "repos": [],
        },
    ],
    "pi-25.4": [
        {
            "issue_number": 121,
            "title": "Potential ODD PI 25.4 Objective: Visualize Web-Optimized Zarr (WOZ) in VEDA (preview)",
            "state": "closed",
            "contributors": [
                ("Max Jones", "maxrjones"),
            ],
            "repos": [],
        },
        {
            "issue_number": 122,
            "title": "Potential 25.4 ODD Objective: Research, develop and document methods for Zarr and VirtualiZarr visualization",
            "state": "closed",
            "contributors": [
                ("Max Jones", "maxrjones"),
                ("Kyle Barron", "kylebarron"),
            ],
            "repos": [],
        },
        {
            "issue_number": 197,
            "title": "ODD PI 25.4 Objective 1: 🎬 TiTiler-CMR is production ready",
            "state": "open",
            "contributors": [
                ("Aimee Barciauskas", "abarciauskas-bgse"),
                ("Henry Rodman", "hrodmn"),
            ],
            "repos": [],
        },
        {
            "issue_number": 198,
            "title": "ODD PI 25.4 Objective 2: 🚀 Dataset support for VEDA instances",
            "state": "closed",
            "contributors": [
                ("Max Jones", "maxrjones"),
                ("Julius Busecke", "jbusecke"),
            ],
            "repos": [],
        },
        {
            "issue_number": 203,
            "title": "ODD PI 25.4 Objective 3: 🗺️Research, develop and document methods for Zarr and VirtualiZarr data services",
            "state": "closed",
            "contributors": [
                ("Max Jones", "maxrjones"),
            ],
            "repos": [],
        },
        {
            "issue_number": 204,
            "title": "ODD PI 25.4 Objective 4: 🛠️ Zarr Development",
            "state": "closed",
            "contributors": [
                ("Davis Bennett", "d-v-b"),
                ("Max Jones", "maxrjones"),
            ],
            "repos": [],
        },
        {
            "issue_number": 205,
            "title": "ODD PI 25.4 Objective 5: 🤗 Community engagement",
            "state": "closed",
            "contributors": [
                ("Sean Harkins", "sharkinsspatial"),
                ("Chuck Daniels", "chuckwondo"),
                ("Max Jones", "maxrjones"),
                ("Aimee Barciauskas", "abarciauskas-bgse"),
            ],
            "repos": [],
        },
        {
            "issue_number": 206,
            "title": "ODD PI 25.4 Objective 6: 📦 Obstore outreach",
            "state": "closed",
            "contributors": [
                ("Chuck Daniels", "chuckwondo"),
                ("Kyle Barron", "kylebarron"),
            ],
            "repos": [],
        },
    ],
    "pi-26.1": [
        {
            "issue_number": 244,
            "title": "ODD PI 26.1 Objective 1: 🗺️ Add dynamic tiling and timeseries support for Virtual Zarr Stores",
            "state": "open",
            "contributors": [
                ("Julius Busecke", "jbusecke"),
                ("Henry Rodman", "hrodmn"),
            ],
            "repos": [
                ("developmentseed", "titiler"),
                ("earth-mover", "icechunk"),
            ],
        },
        {
            "issue_number": 245,
            "title": "ODD PI 26.1 Objective 2: 🌍 Add dynamic tiling and timeseries support for datasets in CMR",
            "state": "open",
            "contributors": [
                ("Aimee Barciauskas", "abarciauskas-bgse"),
                ("Henry Rodman", "hrodmn"),
            ],
            "repos": [
                ("developmentseed", "titiler"),
                ("developmentseed", "titiler-cmr"),
                ("developmentseed", "titiler-lambda-layer"),
                ("developmentseed", "titiler-md-demo"),
                ("nasa", "python_cmr"),
            ],
        },
        {
            "issue_number": 246,
            "title": "ODD PI 26.1 Objective 3: 🤖 Support virtualization of additional data products",
            "state": "closed",
            "contributors": [
                ("Sean Harkins", "sharkinsspatial"),
                ("Max Jones", "maxrjones"),
                ("Julius Busecke", "jbusecke"),
            ],
            "repos": [
                ("zarr-developers", "virtualizarr"),
                ("developmentseed", "obspec-utils"),
                ("virtual-zarr", "virtual-tiff"),
                ("virtual-zarr", "hrrr-parser"),
                ("developmentseed", "async-tiff"),
                ("developmentseed", "virtualizarr-data-pipelines"),
                ("earth-mover", "icechunk"),
            ],
        },
        {
            "issue_number": 247,
            "title": "ODD PI 26.1 Objective 4: 🛰 Explore scalable, cloud native approaches for search, discovery and access of non-gridded data",
            "state": "closed",
            "contributors": [
                ("Sean Harkins", "sharkinsspatial"),
                ("Kyle Barron", "kylebarron"),
            ],
            "repos": [
                ("developmentseed", "obstore"),
                ("developmentseed", "obspec"),
                ("developmentseed", "zarr-datafusion-search"),
                ("geoarrow", "geoarrow-rs"),
                ("datafusion-contrib", "arrow-zarr"),
            ],
        },
        {
            "issue_number": 248,
            "title": "ODD PI 26.1 Objective 5: 🤗 Support community adoption of the technologies incubated by EODC and VEDA",
            "state": "closed",
            "contributors": [
                ("Sean Harkins", "sharkinsspatial"),
                ("Chuck Daniels", "chuckwondo"),
                ("Max Jones", "maxrjones"),
                ("Aimee Barciauskas", "abarciauskas-bgse"),
            ],
            "repos": [
                ("zarr-developers", "geozarr-spec"),
                ("zarr-developers", "zarr-python"),
                ("zarr-conventions", "multiscales"),
                ("zarr-conventions", "geo-proj"),
                ("zarr-conventions", "spatial"),
                ("developmentseed", "datacube-guide"),
                ("developmentseed", "geozarr-examples"),
                ("developmentseed", "warp-resample-profiling"),
                ("pangeo-data", "pangeo.io"),
                ("pangeo-data", "pangeo-docker-images"),
                ("nasa-openscapes", "earthdata-cloud-cookbook"),
            ],
        },
    ],
    "pi-26.2": [
        {
            "issue_number": 304,
            "title": "ODD PI 26.2 Objective 1: 🤖Create virtual Zarr stores for high priority dataset(s)",
            "state": "closed",
            "contributors": [
                ("Tyler", "tylanderson"),
            ],
            "repos": [
                ("developmentseed", "virtualizarr-data-pipelines"),
            ],
        },
        {
            "issue_number": 305,
            "title": "ODD PI 26.2 Objective 2: 🛠️ TiTiler-CMR maintenance + performance",
            "state": "open",
            "contributors": [
                ("Chuck Daniels", "chuckwondo"),
                ("Henry Rodman", "hrodmn"),
            ],
            "repos": [
                ("developmentseed", "titiler"),
                ("developmentseed", "titiler-cmr"),
                ("nasa", "python_cmr"),
                ("cogeotiff", "rio-tiler"),
                ("earthaccess-dev", "earthaccess"),
            ],
        },
        {
            "issue_number": 306,
            "title": "ODD PI 26.2 Objective 3: 🤗 Support community adoption of the technologies incubated by EODC and VEDA",
            "state": "open",
            "contributors": [
                ("Chuck Daniels", "chuckwondo"),
                ("Max Jones", "maxrjones"),
                ("Aimee Barciauskas", "abarciauskas-bgse"),
            ],
            "repos": [
                ("zarr-developers", "geozarr-spec"),
                ("zarr-developers", "zarr-python"),
                ("zarr-conventions", "multiscales"),
                ("zarr-conventions", "geo-proj"),
                ("zarr-conventions", "spatial"),
                ("developmentseed", "datacube-guide"),
                ("developmentseed", "geozarr-examples"),
                ("developmentseed", "warp-resample-profiling"),
                ("pangeo-data", "pangeo.io"),
                ("pangeo-data", "pangeo-docker-images"),
                ("nasa-openscapes", "earthdata-cloud-cookbook"),
                ("virtual-zarr", "virtualzarr.cloud"),
                ("lithops-cloud", "lithops"),
                ("zarr-developers", "zarr-specs"),
                ("zarr-developers", "zarr-extensions"),
                ("zarr-developers", "geozarr-toolkit"),
                ("zarr-developers", "numcodecs"),
                ("zarr-developers", "geozarr-site"),
                ("zarr-developers", "zarr-developers.github.io"),
                ("zarr-developers", "governance"),
                ("zarr-conventions", "template"),
                ("zarr-conventions", "zarr-conventions-spec"),
            ],
        },
        {
            "issue_number": 308,
            "title": "ODD PI 26.2 Objective 5: 🤪 Expand virtualization support for quirky datasets",
            "state": "open",
            "contributors": [
                ("Max Jones", "maxrjones"),
            ],
            "repos": [
                ("zarr-developers", "virtualizarr"),
                ("zarr-developers", "zarr-python"),
                ("developmentseed", "obspec-utils"),
                ("virtual-zarr", "virtual-tiff"),
                ("virtual-zarr", "hrrr-parser"),
                ("developmentseed", "virtualizarr-data-pipelines"),
                ("earth-mover", "icechunk"),
                ("virtual-zarr", "nisar-manifest-explorer"),
                ("virtual-zarr", "mur-manifest-explorer"),
                ("virtual-zarr", "vzviz"),
                ("pydata", "xarray"),
                ("cubed-dev", "cubed"),
            ],
        },
        {
            "issue_number": 309,
            "title": "ODD PI 26.2 Objective 6: 🛰️ Propose unified strategy for virtualization of orbital swath (“L2”) data",
            "state": "open",
            "contributors": [
                ("Sean Harkins", "sharkinsspatial"),
                ("Max Jones", "maxrjones"),
                ("Henry Rodman", "hrodmn"),
            ],
            "repos": [
                ("zarr-developers", "virtualizarr"),
                ("developmentseed", "obspec-utils"),
                ("virtual-zarr", "virtual-tiff"),
                ("developmentseed", "obstore"),
                ("developmentseed", "obspec"),
                ("developmentseed", "zarr-datafusion-search"),
                ("geoarrow", "geoarrow-rs"),
                ("developmentseed", "async-tiff"),
                ("datafusion-contrib", "arrow-zarr"),
            ],
        },
        {
            "issue_number": 319,
            "title": "ODD PI 26.2 Objective 7: 🌐 Client-side raster rendering (deck.gl-raster)",
            "state": "closed",
            "contributors": [
                ("Kyle Barron", "kylebarron"),
            ],
            "repos": [
                ("developmentseed", "deck.gl-raster"),
            ],
        },
        {
            "issue_number": 331,
            "title": "ODD PI 26.? Objective ?: WASM chunk codec research and PoC",
            "state": "open",
            "contributors": [
                ("Jarrett Keifer", "jkeifer"),
            ],
            "repos": [],
        },
    ],
    "pi-26.3": [
        {
            "issue_number": 307,
            "title": "ODD PI 26.3 Objective 8: 📈 Finalize Design for Zarr + VirtualiZarr Time Series API [Carry over from 26.2] [Stretch: start implementation]",
            "state": "open",
            "contributors": [
                ("Henry Rodman", "hrodmn"),
            ],
            "repos": [
                ("developmentseed", "titiler"),
                ("developmentseed", "titiler-lambda-layer"),
                ("developmentseed", "titiler-md-demo"),
            ],
        },
        {
            "issue_number": 346,
            "title": "ODD PI 26.3 Objective 1: 🤖 Develop + Maintain the Virtual Zarr Ecosystem",
            "state": "open",
            "contributors": [
                ("Max Jones", "maxrjones"),
                ("Tyler", "tylanderson"),
                ("Harshini ", "HarshiniGirish"),
            ],
            "repos": [
                ("zarr-developers", "virtualizarr"),
                ("virtual-zarr", "virtual-tiff"),
                ("earth-mover", "icechunk"),
                ("virtual-zarr", "virtualzarr.cloud"),
            ],
        },
        {
            "issue_number": 347,
            "title": "ODD PI 26.3 Objective 2: 🌳 Evolve the Zarr Ecosystem",
            "state": "open",
            "contributors": [
                ("Davis Bennett", "d-v-b"),
                ("Chuck Daniels", "chuckwondo"),
                ("Max Jones", "maxrjones"),
            ],
            "repos": [
                ("zarr-developers", "geozarr-spec"),
                ("zarr-developers", "zarr-python"),
                ("zarr-conventions", "multiscales"),
                ("zarr-conventions", "geo-proj"),
                ("zarr-conventions", "spatial"),
                ("zarr-developers", "zarr-specs"),
                ("zarr-developers", "zarr-extensions"),
                ("zarr-developers", "geozarr-toolkit"),
                ("zarr-developers", "numcodecs"),
                ("zarr-developers", "geozarr-site"),
                ("zarr-developers", "zarr-developers.github.io"),
            ],
        },
        {
            "issue_number": 348,
            "title": "ODD PI 26.3 Objective 3: 📝 Cloud-Optimized Data Guidance",
            "state": "open",
            "contributors": [
                ("Aimee Barciauskas", "abarciauskas-bgse"),
                ("Henry Rodman", "hrodmn"),
                ("Siddharth Chaudhary", "siddharth0248"),
            ],
            "repos": [],
        },
        {
            "issue_number": 349,
            "title": "ODD PI 26.3 Objective 4: 🤗 Community Engagement",
            "state": "open",
            "contributors": [
                ("Sean Harkins", "sharkinsspatial"),
                ("Chuck Daniels", "chuckwondo"),
                ("Max Jones", "maxrjones"),
                ("Aimee Barciauskas", "abarciauskas-bgse"),
            ],
            "repos": [
                ("pangeo-data", "pangeo.io"),
            ],
        },
        {
            "issue_number": 350,
            "title": "ODD PI 26.3 Objective 5: 🛠️ TiTiler-CMR Support",
            "state": "open",
            "contributors": [
                ("Chuck Daniels", "chuckwondo"),
                ("Aimee Barciauskas", "abarciauskas-bgse"),
            ],
            "repos": [
                ("developmentseed", "titiler"),
                ("developmentseed", "titiler-cmr"),
                ("developmentseed", "titiler-lambda-layer"),
                ("developmentseed", "titiler-md-demo"),
                ("cogeotiff", "rio-tiler"),
            ],
        },
        {
            "issue_number": 351,
            "title": "ODD PI 26.3 Objective 6: 🛰️ Analytics-scale metadata stores",
            "state": "open",
            "contributors": [
                ("Sean Harkins", "sharkinsspatial"),
                ("Henry Rodman", "hrodmn"),
            ],
            "repos": [
                ("developmentseed", "zarr-datafusion-search"),
                ("developmentseed", "lazycogs"),
            ],
        },
        {
            "issue_number": 352,
            "title": "ODD PI 26.3 Objective 7: 🌐 Browser-based visualization + analysis",
            "state": "open",
            "contributors": [
                ("Aimee Barciauskas", "abarciauskas-bgse"),
                ("Kyle Barron", "kylebarron"),
            ],
            "repos": [
                ("developmentseed", "deck.gl-raster"),
                ("developmentseed", "lonboard"),
            ],
        },
    ],
}
