TIME_RANGE = ("20250701", "20250801")

# Name, username, start date, end date
USERS = [
    # ODD
    ("Max Jones", "maxrjones", None, None),
    ("Davis Bennett", "d-v-b", "20250425", None),
    ("Kyle Barron", "kylebarron", None, None),
    ("Aimee Barciauskas", "abarciauskas-bgse", None, None),
    ("Chunk Daniels", "chuckwondo", None, None),
    ("Sean Harkins", "sharkinsspatial", None, None),
    ("Henry Rodman", "hrodmn", None, None),
    ("Julius Busecke", "jbusecke", "20250623", None),
    ("Negin Sobhani", "negin513", "20250729", None),
    # Science support
    ("Alex Mandel", "wildintellect", None, None),
    ("Julia Signell", "jsignell", None, None),
    ("Sheyenne Kirkland", "smk0033", None, None),
    ("Zac Deziel", "zacdezgeo", None, None),
    ("Nathan Zimmermann", "moradology", None, None),
    # JupyterHub
    ("Sanjay Bhangar", "batpad", None, None),
    ("Tarashish Mishra", "sunu", None, None)
]


REPOS = [
    ("apache", "arrow-rs"),
    ("boettiger-lab", "earthdatalogin),
    ("conda-forge", "r-lasr-feedstock"),
    ("cloudnativegeo", "cloud-optimized-geospatial-formats-guide"),
    ("developmentseed", "async-tiff"),
    ("developmentseed", "eoAPI"),
    ("developmentseed", "eoAPI-cdk"),
    ("developmentseed", "geozarr-examples"),
    ("developmentseed", "lonboard"),
    ("developmentseed", "mursst-icechunk-updater"),
    ("developmentseed", "rio-stac"),
    ("developmentseed", "tilebench"),
    ("developmentseed", "titiler"),
    ("developmentseed", "titiler-cmr"),
    ("developmentseed", "titiler-lambda-layer"),
    ("developmentseed", "titiler-md-demo"),
    ("developmentseed", "titiler-stacapi"),
    ("developmentseed", "warp-resample-profiling"),
    ("developmentseed", "obspec"),
    ("developmentseed", "obstore"),
    ("earth-mover", "icechunk-nasa"),
    ("earth-mover", "icechunk"),
    ("flatgeobuf", "flatgeobuf"),
    ("geoarrow", "deck.gl-layers"),
    ("geoarrow", "geoarrow-rs"),
    ("geopandas", "geopandas"),
    ("georust", "geo-svg"),
    ("holoviz", "hvplot"),
    ("pangeo-data", "pangeo-docker-images"),
    ("pangeo-data", "pangeo.io"),
    ("NASAWaterInsight", "NLDAS-3"),
    ("nasa", "python_cmr"),
    ("NASA-IMPACT", "veda-odd"),
    ("NASA-IMPACT", "veda-ui"),
    ("NASA-IMPACT", "veda-docs"),
    ("NASA-IMPACT", "zarr-visualization-report"),
    ("nasa-openscapes", "earthdata-cloud-cookbook"),
    ("nsidc", "earthaccess"),
    ("nsidc", "cloud-optimized-icesat2"),
    ("numbagg", "numbagg"),
    ("pydata", "xarray"),
    ("radiantearth", "stac-spec"),
    ("stac-extensions", "zarr"),
    ("stac-utils", "stac-fastapi-pgstac"),
    ("stac-utils", "rustac-py"),
    ("stac-utils", "pgstac"),
    ("stac-utils", "pystac"),
    ("stac-utils", "pystac-client"),
    ("stac-utils", "xpystac"),
    ("virtual-zarr", "hrrr-parser"),
    ("virtual-zarr", "virtual-tiff"),
    ("virtual-zarr", "obspec-utils"),
    ("virtual-zarr", "nldas-icechunk"),
    ("zarr-developers", "zarr-python"),
    ("zarr-developers", "geozarr-spec"),
    ("zarr-developers", "VirtualiZarr"),
    ("2i2c-org", "jupyterhub-fancy-profiles"),
    ("2i2c-org", "infrastructure"),
]
