name: Update Reports

on:
  schedule:
    # Run every Monday at 9 AM ET (14:00 UTC)
    - cron: '0 14 * * 1'
  workflow_dispatch:

jobs:
  reports:
    uses: NASA-IMPACT/dse-oss-reports/.github/workflows/reports.yml@82a1ac63978b5440d0f0d1de83fc46419171bdb8  # v0.3.0
    permissions:
      contents: write
      pull-requests: write
    with:
        dse-oss-reports-ref: 82a1ac63978b5440d0f0d1de83fc46419171bdb8
    secrets:
      pat: ${{ secrets.GH_ODD_PAT }}
