name: Update Reports

on:
  schedule:
    # Run every Monday at 9 AM ET (14:00 UTC)
    - cron: '0 14 * * 1'
  workflow_dispatch:

jobs:
  reports:
    uses: NASA-IMPACT/dse-oss-reports/.github/workflows/reports.yml@161e544667d4805dc2c8ec439dfed028699c7ed4
    permissions:
      contents: write
      pull-requests: write
    with:
      dse-oss-reports-ref: 161e544667d4805dc2c8ec439dfed028699c7ed4
    secrets:
      pat: ${{ secrets.GH_ODD_PAT }}
